name: wtbgassistant
description: WTbgA

publish_to: 'none'

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  archive: ^3.5.1
  audioplayers: ^6.0.0
  animated_text_kit: ^4.2.2
  collection: ^1.18.0
  color: 3.0.0
  device_info_plus: ^10.1.0
  dio: ^5.4.3
  dynamic_color: ^1.6.8
  firebase_dart: ^1.1.4
  firebase_dart_flutter: ^1.1.4
  fluent_ui: ^4.8.7
  flutter_acrylic: ^1.0.0+2
  flutter_colorpicker: ^1.1.0
  flutter_riverpod: ^2.5.1
  gap: ^3.0.1
  hotkey_manager: ^0.2.3
  intl: ^0.19.0
  local_notifier: ^0.1.6
  openrgb: ^0.2.5
  path: ^1.8.1
  path_provider: ^2.1.3
  percent_indicator: ^4.2.3
  shared_preferences: ^2.2.3
  system_info2: ^4.0.0
  tray_manager: ^0.2.3
  url_launcher: ^6.2.6
  version: ^3.0.2
  win32: ^5.5.1
  win32_registry: ^1.1.3
  window_manager: ^0.3.9
  window_watcher: ^0.0.2

dev_dependencies:
  dependency_validator: ^4.0.0

  flutter_lints: ^4.0.0

dependency_overrides:
  intl: ^0.19.0



# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/version/
    - assets/icons/
    - assets/sounds/
    - assets/fm/
