name: wtbgassistant
description: WTbgA
version: 3.0.14-pre

publish_to: "none"

environment:
  sdk: ">=3.8.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  archive: ^4.0.1
  audioplayers: ^6.0.0
  animated_text_kit: ^4.2.2
  collection: ^1.19.0
  color: 3.0.0
  device_info_plus: ^11.2.0
  dio: ^5.4.3
  dynamic_color: ^1.6.8
  firebase_dart: ^1.1.4
  firebase_dart_flutter: ^1.1.4
  fluent_ui: ^4.8.7
  flutter_acrylic: ^1.1.4
  flutter_colorpicker: ^1.1.0
  flutter_riverpod: ^2.5.1
  gap: ^3.0.1
  hotkey_manager: ^0.2.3
  intl: ^0.20.2
  local_notifier: ^0.1.6
  openrgb: ^0.2.5
  path: ^1.8.1
  path_provider: ^2.1.3
  percent_indicator: ^4.2.3
  package_info_plus: ^8.0.1
  shared_preferences: ^2.2.3
  system_info2: ^4.0.0
  tray_manager: ^0.5.0
  url_launcher: ^6.2.6
  version: ^3.0.2
  win32: ^5.5.1
  win32_registry: ^2.1.0
  window_manager: ^0.5.0
  window_watcher: ^0.0.2
  simplytranslate: ^2.2.1+3

dev_dependencies:
  dependency_validator: ^5.0.2

  flutter_lints: ^6.0.0


# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/sounds/
    - assets/fm/
